In [2]:
import numpy as np

In [4]:
integers = np.array([10,20,30,40,50])

In [7]:
print(integers)

[10 20 30 40 50]


In [10]:
integers[1]

20

In [11]:
integers[0] = 3
integers

array([ 3, 20, 30, 40, 50])

In [13]:
print(integers)

[ 3 20 30 40 50]


In [15]:
integers[0] = 6.7
integers

array([ 6, 20, 30, 40, 50])

In [17]:
integers.dtype

dtype('int64')

In [18]:
smallerIntegers = np.array([1,2,3,4], dtype=np.int8)
smallerIntegers

array([1, 2, 3, 4], dtype=int8)

In [19]:
integers.nbytes

40

In [22]:
smallerIntegers.nbytes

4

In [24]:
overflow = np.array([127, 128, 129], dtype = np.int8)
overflow

array([ 127, -128, -127], dtype=int8)

In [26]:
overflow2 = np.array([125, 126, 127], dtype = np.int8)
overflow2

array([125, 126, 127], dtype=int8)

In [28]:
floats = np.array([1.2, 2.3, 3.4, 5.1, 8.3])
print(floats)

[1.2 2.3 3.4 5.1 8.3]


In [29]:
floats.dtype

dtype('float64')