### Creating arrays from Lists and other Python structures

In [1]:
import numpy as np

In [3]:
first_list = [1,2,3,4,5,6,7,8,9,10]

In [4]:
first_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [5]:
first_array = np.array(first_list)

In [6]:
first_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
second_list = [1, 2, 3, -1.23, 50, 128000.56, 4.56]

In [9]:
second_array = np.array(second_list)

In [10]:
second_array

array([ 1.0000000e+00,  2.0000000e+00,  3.0000000e+00, -1.2300000e+00,
        5.0000000e+01,  1.2800056e+05,  4.5600000e+00])

In [11]:
second_array.dtype

dtype('float64')

In [12]:
mixed_list = [1, "elly", 2, "evi eller bea"]
mixed_list

[1, 'elly', 2, 'evi eller bea']

In [13]:
mixed_array = np.array(mixed_list)
mixed_array

array(['1', 'elly', '2', 'evi eller bea'], dtype='<U21')

In [14]:
mixed_array.dtype

dtype('<U21')

In [16]:
first_tuple = (5, 10, 15, 20, 25, 30)

In [17]:
array_from_tuple = np.array(first_tuple)

In [19]:
array_from_tuple

array([ 5, 10, 15, 20, 25, 30])

In [20]:
array_from_tuple.dtype

dtype('int64')

In [22]:
array_from_tuple.ndim

1

In [ ]:
multi_dim_list = [[[0,1,2],[3]], [[7,8,9],[]]]