### Intrinsic Numpy array creation

In [2]:
import numpy as np

In [3]:
integersArray = np.arange(10)

In [4]:
integersArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
fra100Til129 = np.arange(100,130)

In [6]:
fra100Til129

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129])

In [7]:
evenSteven = np.arange(100,150,2)

In [8]:
evenSteven

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148])

In [9]:
first_floats_arr = np.linspace(10,20)

In [10]:
first_floats_arr

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [11]:
# slenger vi inn et tredje argument i linspace sier 
# det hvor mange samples vi vil ha (default er 50)

In [12]:
second_floats_arr = np.linspace(10,20,5)

In [13]:
second_floats_arr

array([10. , 12.5, 15. , 17.5, 20. ])

In [14]:
first_random_arr = np.random.rand(10)

In [15]:
first_random_arr

array([0.72202327, 0.66280545, 0.44841446, 0.54991863, 0.32675201,
       0.94904462, 0.16452298, 0.9478512 , 0.47979582, 0.05144713])

In [16]:
multidimensional_random_arr = np.random.rand(3,5)

In [17]:
multidimensional_random_arr

array([[0.82117024, 0.78571463, 0.16501665, 0.54798171, 0.59076831],
       [0.48608965, 0.09241928, 0.95219708, 0.1621771 , 0.81697282],
       [0.52013685, 0.43396696, 0.24280948, 0.57201927, 0.57316474]])

In [19]:
random_integers = np.random.randint(14,40,8)

In [20]:
random_integers

array([20, 35, 21, 19, 22, 33, 25, 18])