In [1]:
import numpy as np

In [4]:
firstArr = np.arange(1,13,1)
firstArr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [5]:
secondArr = np.reshape(firstArr, (6,2))
secondArr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [6]:
thirdArr = np.reshape(firstArr, (2,3,2))
thirdArr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [7]:
firstArr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [9]:
fourthArr = np.reshape(firstArr, (5,3))
fourthArr

ValueError: cannot reshape array of size 12 into shape (5,3)

In [11]:
twoD = np.array([[1,2,3,4],[5,6,7,8]])
print(twoD)
print(twoD.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [16]:
oneD = np.reshape(twoD, 8)
print(oneD)
print(oneD.ndim)

[1 2 3 4 5 6 7 8]
1


In [17]:
another2D = np.array([[1,2],[3,4],[5,6]])
print(another2D)
print(another2D.ndim)

[[1 2]
 [3 4]
 [5 6]]
2


In [18]:
another1D = np.reshape(another2D, 6)
print(another1D)
print(another1D.ndim)

[1 2 3 4 5 6]
1


In [19]:
flatArr = np.reshape(thirdArr, -1)
print(flatArr)
print(flatArr.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


In [20]:
flattenArr = thirdArr.flatten()
print(flattenArr)
print(flattenArr.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


In [22]:
ravelArr = thirdArr.ravel()
print(ravelArr)
print(ravelArr.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


In [26]:
thirdArr[1,2,1]=1200
flatArr[0]=100
flattenArr[1]=200
ravelArr[2]=300

print("thirdArr", thirdArr)
print("flatArr", flatArr)
print("flattenArr", flattenArr)
print("ravelArr", ravelArr)

thirdArr [[[ 100    2]
  [ 300    4]
  [   5    6]]

 [[   7    8]
  [   9   10]
  [  11 1200]]]
flatArr [ 100    2  300    4    5    6    7    8    9   10   11 1200]
flattenArr [  1 200   3   4   5   6   7   8   9  10  11  12]
ravelArr [ 100    2  300    4    5    6    7    8    9   10   11 1200]


In [27]:
thirdArr

array([[[ 100,    2],
        [ 300,    4],
        [   5,    6]],

       [[   7,    8],
        [   9,   10],
        [  11, 1200]]])