In [1]:
import numpy as np

In [2]:
twoDimArr = np.reshape(np.arange(12), (3,4))
twoDimArr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
print(twoDimArr[1,1])
print(twoDimArr[1][1])
print(twoDimArr[1])

5
5
[4 5 6 7]


In [5]:
threeDimArr = np.reshape(np.arange(3*4*5), (3,4,5))
threeDimArr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [7]:
threeDimArr[0,2,3]

13

In [8]:
threeDimArr[2,-1,-1]

59

In [19]:
oneDimArr = np.arange(10)
print(oneDimArr[2:5])
print(oneDimArr[:5])
print(oneDimArr[4:])
print(oneDimArr[-3])
print(oneDimArr[-3:])
print(oneDimArr[7:])
print(oneDimArr[::2])
print(oneDimArr[1::2])

[2 3 4]
[0 1 2 3 4]
[4 5 6 7 8 9]
7
[7 8 9]
[7 8 9]
[0 2 4 6 8]
[1 3 5 7 9]


In [15]:
threeDimArr[0,1:2]

array([[5, 6, 7, 8, 9]])

In [17]:
threeDimArr[0,1][::2]

array([5, 7, 9])

In [22]:
print(twoDimArr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [25]:
print(twoDimArr[1:,1:])

[[ 5  6  7]
 [ 9 10 11]]


In [26]:
print(twoDimArr[2:,1:])

[[ 9 10 11]]


In [27]:
print(twoDimArr[:,2:])

[[ 2  3]
 [ 6  7]
 [10 11]]


In [28]:
threeDimArr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [29]:
print(threeDimArr[0,1])

[5 6 7 8 9]


In [31]:
print(threeDimArr[0:,1])

[[ 5  6  7  8  9]
 [25 26 27 28 29]
 [45 46 47 48 49]]


In [32]:
print(threeDimArr[0:,1:])

[[[ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


In [33]:
print(threeDimArr[::])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


In [34]:
print(threeDimArr[0:1:])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]]


In [37]:
a = np.array([1,2,3,4,5])
print(a[1:])
print(a[:3])
print(a[::2])

[2 3 4 5]
[1 2 3]
[1 3 5]


In [39]:
min2d = np.array([[10,11,12,13,14],
                  [15,16,17,18,19],
                  [20,21,22,23,24],
                  [25,26,27,28,29]
                ])
print(min2d)

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [40]:
print(min2d[1:3, 1:3])

[[16 17]
 [21 22]]


In [43]:
print(threeDimArr[:2,2:,1:4])

[[[11 12 13]
  [16 17 18]]

 [[31 32 33]
  [36 37 38]]]


In [44]:
monster = np.array([[[10,11,12],[13,14,15], [16,17,18]],
                    [[20,21,22],[23,24,25], [26,27,28]],
                    [[30,31,32],[33,34,35],[36,37,38]]])
print(monster)

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[20 21 22]
  [23 24 25]
  [26 27 28]]

 [[30 31 32]
  [33 34 35]
  [36 37 38]]]


In [45]:
print(monster[0:2,1:3,0:2])

[[[13 14]
  [16 17]]

 [[23 24]
  [26 27]]]


In [46]:
print(monster[:2,1:3,0:2])

[[[13 14]
  [16 17]]

 [[23 24]
  [26 27]]]


In [47]:
print(monster[:2,1:,:2])

[[[13 14]
  [16 17]]

 [[23 24]
  [26 27]]]


In [48]:
twoDimArr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
print(twoDimArr[1:,1:])

[[ 5  6  7]
 [ 9 10 11]]


In [50]:
print(twoDimArr[1,:])

[4 5 6 7]


In [51]:
twoDimArr[:,2]

array([ 2,  6, 10])

In [ ]:
twoDimArr[:,]