In [1]:
import numpy as np

In [5]:
firstArr = np.array([1,2,3,5])
firstArr

array([1, 2, 3, 5])

In [21]:
anotherArr = np.insert(firstArr, 3, 4)
anotherArr

array([1, 2, 3, 4, 5])

In [25]:
appendArr = np.append(anotherArr, 6)
appendArr

array([1, 2, 3, 4, 5, 6])

In [29]:
delArr = np.delete(appendArr, 2)
delArr

array([1, 2, 4, 5, 6])

In [30]:
unsorted = np.random.randint(0,20,20)
unsorted

array([ 8, 19, 13, 12, 10,  2,  0,  0,  0,  1,  4,  8,  6, 17,  2,  7, 14,
       11, 15,  4])

In [32]:
sorted = np.sort(unsorted)
print(sorted)

[ 0  0  0  1  2  2  4  4  6  7  8  8 10 11 12 13 14 15 17 19]


In [33]:
unsorted_2D = np.array([[5,3,6,2,1],[6,7,3,56,1]])
unsorted_2D

array([[ 5,  3,  6,  2,  1],
       [ 6,  7,  3, 56,  1]])

In [34]:
print(np.sort(unsorted_2D))

[[ 1  2  3  5  6]
 [ 1  3  6  7 56]]


In [35]:
farger = np.array(["rød", "gul", "grønn", "blå", "lilla", "rosa", "brun", "svart", "hvit"])
farger

array(['rød', 'gul', 'grønn', 'blå', 'lilla', 'rosa', 'brun', 'svart',
       'hvit'], dtype='<U5')

In [36]:
print(farger)

['rød' 'gul' 'grønn' 'blå' 'lilla' 'rosa' 'brun' 'svart' 'hvit']


In [38]:
print(np.sort(farger))

['blå' 'brun' 'grønn' 'gul' 'hvit' 'lilla' 'rosa' 'rød' 'svart']
