In [1]:
import numpy as np

In [2]:
students_ids_number = np.array([1111, 1212, 1313, 1414, 1515, 1616, 1717, 1818])
students_ids_number

array([1111, 1212, 1313, 1414, 1515, 1616, 1717, 1818])

In [7]:
students_ids_number_reg = students_ids_number
print(f"id of students_ids_number is {id(students_ids_number)}")
print(f"id of students_ids_number_reg is {id(students_ids_number_reg)}")

id of students_ids_number is 140266258351472
id of students_ids_number_reg is 140266258351472


In [8]:
# Vi ser ovenfor at de har samme adresse i minne.
# Forandre vi en, forandrer vi den andre.

In [9]:
students_ids_number_reg[1] = 2222
print(students_ids_number)
print(students_ids_number_reg)

[1111 2222 1313 1414 1515 1616 1717 1818]
[1111 2222 1313 1414 1515 1616 1717 1818]


In [10]:
print(students_ids_number == students_ids_number_reg)

[ True  True  True  True  True  True  True  True]


In [11]:
students_ids_number_cp = students_ids_number.copy()
print(id(students_ids_number), "students_ids_number")
print(id(students_ids_number_cp), "students_ids_number_cp")

140266258351472 students_ids_number
140266267484784 students_ids_number_cp


In [12]:
# Siden de har forskjellige adresser, vil ikke endring i en av dem
# reflekteres i den andre

In [13]:
students_ids_number[0] = 1000
print(f"Original: {students_ids_number}")
print(f"Copy: {students_ids_number_cp}")

Original: [1000 2222 1313 1414 1515 1616 1717 1818]
Copy: [1111 2222 1313 1414 1515 1616 1717 1818]


In [14]:
############################
#     VIEWS                #
############################

In [15]:
students_ids_number_view = students_ids_number.view()

In [17]:
students_ids_number[7] = 1010
students_ids_number_view[0] = 2000
print("original: ", students_ids_number)
print("view: ", students_ids_number)

original:  [2000 2222 1313 1414 1515 1616 1717 1010]
view:  [2000 2222 1313 1414 1515 1616 1717 1010]


In [19]:
# Vi ser de påvirker hverandre
# Underlig nok har de ikke samme adresse
# Men gir mening at det er anderledes enn en assignment
# En view har påvirkning mellom original og klone, men deler likevel ikke adresse

In [20]:
print(id(students_ids_number), "students_ids_number")
print(id(students_ids_number_cp), "students_ids_number_view")

140266258351472 students_ids_number
140266267484784 students_ids_number_view


In [21]:
############################
#     BASE                #
############################

In [22]:
# Hvis base returnerer None, sier vi at arrayen er eieren av dataen

In [25]:
print("students_ids_number.base ->", students_ids_number.base)
print("students_ids_number_reg.base ->", students_ids_number_reg.base)
print("students_ids_number_cp.base ->", students_ids_number_cp.base)
print("students_ids_number_view.base ->", students_ids_number_view.base)

students_ids_number.base -> None
students_ids_number_reg.base -> None
students_ids_number_cp.base -> None
students_ids_number_view.base -> [2000 2222 1313 1414 1515 1616 1717 1010]
