In [1]:
import numpy as np

In [18]:
firstArr = np.arange(1,11)
secondArr = np.arange(11, 21)
print("firstArr:", firstArr)
print("secondArr:", secondArr)

firstArr: [ 1  2  3  4  5  6  7  8  9 10]
secondArr: [11 12 13 14 15 16 17 18 19 20]


In [4]:
conArr = np.concatenate((firstArr, secondArr))
conArr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [5]:
# syntaks for concatenate
# np.concatenate(arrayene, akse (default er 0))

In [7]:
third2D = np.array([[1,2,3,4,5],[6,7,8,9,10]])
fourth2D = np.array([[11,12,13,14,15],[16,17,18,19,20]])
con2D = np.concatenate((third2D,fourth2D), axis=1)
print(con2D)

[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]


In [9]:
con2D = np.concatenate((third2D,fourth2D)) # default er axis = 0
print(con2D)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [28]:
stackArr = np.stack((firstArr, secondArr),axis=0)
print(stackArr)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [23]:
print(np.concatenate((firstArr, secondArr)))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [25]:
h_stack = np.hstack((firstArr,secondArr))
print(h_stack)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [27]:
v_stack=np.vstack((firstArr, secondArr))
print(v_stack)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [29]:
enTilTolv = np.arange(1,13)
print(enTilTolv)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [33]:
firstSplit = np.array_split(enTilTolv, 4)
secondSplit = np.array_split(enTilTolv, 8)
print(enTilTolv)
print(firstSplit)
print(secondSplit)
print(firstSplit[1])

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([9]), array([10]), array([11]), array([12])]
[4 5 6]


In [34]:
print(third2D)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [35]:
print(np.reshape(np.arange(1,11),(2,5)))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [38]:
hs_arr = np.hsplit(third2D, 5) #får 5 todimensjonelle arrays
print(hs_arr)

[array([[1],
       [6]]), array([[2],
       [7]]), array([[3],
       [8]]), array([[4],
       [9]]), array([[ 5],
       [10]])]


In [37]:
print(hs_arr[0])

[[1]
 [6]]


In [40]:
vs_arr = np.vsplit(third2D, 2)
print(vs_arr)
print(vs_arr[0])

[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]])]
[[1 2 3 4 5]]
