In [1]:
import numpy as np

In [2]:
a=np.arange(1,11)
b=np.arange(21,31)
print("a", a)
print("b", b)

a [ 1  2  3  4  5  6  7  8  9 10]
b [21 22 23 24 25 26 27 28 29 30]


In [3]:
a+b

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [11]:
c = a + b
print("c", c)

c [22 24 26 28 30 32 34 36 38 40]


In [5]:
print(b-a)

[20 20 20 20 20 20 20 20 20 20]


In [6]:
print(a*b)

[ 21  44  69  96 125 156 189 224 261 300]


In [7]:
print(b/a)

[21.         11.          7.66666667  6.          5.          4.33333333
  3.85714286  3.5         3.22222222  3.        ]


In [8]:
d = np.arange(2,12)
print("d", d)

d [ 2  3  4  5  6  7  8  9 10 11]


In [9]:
print(a**d)

[           1            8           81         1024        15625
       279936      5764801    134217728   3486784401 100000000000]


In [10]:
print(a*2)

[ 2  4  6  8 10 12 14 16 18 20]


In [12]:
print(np.add(a,b))

[22 24 26 28 30 32 34 36 38 40]


In [13]:
print(np.subtract(a,b))

[-20 -20 -20 -20 -20 -20 -20 -20 -20 -20]


In [14]:
np.divide(b,a)

array([21.        , 11.        ,  7.66666667,  6.        ,  5.        ,
        4.33333333,  3.85714286,  3.5       ,  3.22222222,  3.        ])

In [15]:
np.multiply(a,b)

array([ 21,  44,  69,  96, 125, 156, 189, 224, 261, 300])

In [16]:
np.mod(b,a)

array([0, 0, 2, 0, 0, 2, 6, 4, 2, 0])

In [17]:
np.power(a,d)

array([           1,            8,           81,         1024,
              15625,       279936,      5764801,    134217728,
         3486784401, 100000000000])

In [18]:
j = [4,9,16,25,36]
print(np.sqrt(j))

[2. 3. 4. 5. 6.]
