In [1]:
import numpy as np

In [2]:
minArray = np.array([1,2,3,1,2,3])
print(minArray)

[1 2 3 1 2 3]


In [3]:
print(np.unique(minArray))

[1 2 3]


In [5]:
dinArr = np.array([[1,1,2,1],[3,1,2,1],[1,1,2,1],[7,1,1,1]])
print(dinArr)

[[1 1 2 1]
 [3 1 2 1]
 [1 1 2 1]
 [7 1 1 1]]


In [6]:
# første og tredje rad helt like
# andre og fjerde kolonne helt like

In [13]:
print(np.unique(dinArr))

[1 2 3 7]


In [12]:
print(np.unique(dinArr, axis=0))
print("-----------------")
print(np.unique(dinArr, axis=1))

[[1 1 2 1]
 [3 1 2 1]
 [7 1 1 1]]
-----------------
[[1 1 2]
 [1 3 2]
 [1 1 2]
 [1 7 1]]


In [14]:
print(dinArr)

[[1 1 2 1]
 [3 1 2 1]
 [1 1 2 1]
 [7 1 1 1]]


In [15]:
np.unique(minArray, return_index=True)

(array([1, 2, 3]), array([0, 1, 2]))

In [16]:
# gir først en array med unike verdier, så en array med indeksen hvor de forekom første gang

In [18]:
np.unique(dinArr, return_counts=True)

(array([1, 2, 3, 7]), array([11,  3,  1,  1]))

In [19]:
# Først arrayen med unike verdier, så antallet verdiene forekommer