In [1]:
import numpy as np

In [2]:
first_2dimarr = np.arange(12).reshape((3,4))
print(first_2dimarr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [3]:
transposed = np.transpose(first_2dimarr)
print(transposed)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [4]:
second_2dimarr = np.arange(6).reshape(3,2)
print(second_2dimarr)

[[0 1]
 [2 3]
 [4 5]]


In [18]:
transposed = np.transpose(second_2dimarr)
print(transposed)
print("-------------")
print(second_2dimarr)
print(second_2dimarr.shape)

[[0 2 4]
 [1 3 5]]
-------------
[[0 1]
 [2 3]
 [4 5]]
(3, 2)


In [7]:
transposed = np.transpose(second_2dimarr,(1,0))
print(transposed)

[[0 2 4]
 [1 3 5]]


In [14]:
first_3dimarr = np.arange(24).reshape(2,3,4)
print(first_3dimarr)
print("shape:", first_3dimarr.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
shape: (2, 3, 4)


In [15]:
axisFirst = np.moveaxis(first_3dimarr, 0 , -1)
print(axisFirst)
print("shape:",axisFirst.shape)

[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]
shape: (3, 4, 2)


In [16]:
axisSecond = np.moveaxis(first_3dimarr, 1,-1)
print(axisSecond)
print("shape:", axisSecond.shape)

[[[ 0  4  8]
  [ 1  5  9]
  [ 2  6 10]
  [ 3  7 11]]

 [[12 16 20]
  [13 17 21]
  [14 18 22]
  [15 19 23]]]
shape: (2, 4, 3)
